PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS `BLOB` (
    ID INTEGER PRIMARY KEY,
    CONTENT BLOB NOT NULL,
    SHA256 TEXT NOT NULL 
);

CREATE TABLE IF NOT EXISTS `COMMIT` (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UNIQUE_ID TEXT NOT NULL,
    AUTHOR_EMAIL TEXT NOT NULL,
    AUTHOR_NAME TEXT NOT NULL,
    DATE TEXT NOT NULL,
    PARENT_COMMIT_ID INTEGER,
    FOREIGN KEY(PARENT_COMMIT_ID) REFERENCES `COMMIT`(id)
);

CREATE TABLE IF NOT EXISTS `COMMIT_BLOB` (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMMIT_ID INTEGER NOT NULL,
    BLOB_ID INTEGER,
    PATH TEXT NOT NULL,
    FOREIGN KEY(COMMIT_ID) REFERENCES `COMMIT`(id),
    FOREIGN KEY(BLOB_ID) REFERENCES `BLOB`(id)
);

CREATE TABLE IF NOT EXISTS `SPRINT`(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT UNIQUE NOT NULL,
    BASE_COMMIT_ID INTEGER,
    LAST_COMMIT_ID INTEGER,
    FOREIGN KEY(BASE_COMMIT_ID) REFERENCES `COMMIT`(id)
);

CREATE TABLE IF NOT EXISTS `CONFIG` (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CONFIG_KEY TEXT UNIQUE NOT NULL,
    CONFIG_VALUE TEXT NOT NULL
); 

INSERT INTO `CONFIG` (CONFIG_KEY, CONFIG_VALUE)
VALUES ('AUTHOR_EMAIL', '');

INSERT INTO `CONFIG` (CONFIG_KEY, CONFIG_VALUE)
VALUES ('AUTHOR_NAME', '');

INSERT INTO `CONFIG` (CONFIG_KEY, CONFIG_VALUE)
VALUES ('CURRENT_SPRINT', 'main');

