PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS `BLOB` (
    ID TEXT PRIMARY KEY,
    CONTENT BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS `COMMIT` (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UNIQUE_ID TEXT NOT NULL,
    AUTHOR_EMAIL TEXT NOT NULL,
    AUTHOR_NAME TEXT NOT NULL,
    DATE TEXT NOT NULL,
    PARENT_COMMIT_ID INTEGER,
    FOREIGN KEY(PARENT_COMMIT_ID) REFERENCES `COMMIT`(id)
);

CREATE TABLE IF NOT EXISTS `COMMIT_BLOB` (
    COMMIT_ID INTEGER NOT NULL,
    BLOB_ID TEXT NOT NULL,
    PATH TEXT NOT NULL,
    PRIMARY KEY (COMMIT_ID, path),
    FOREIGN KEY(COMMIT_ID) REFERENCES `COMMIT`(id),
    FOREIGN KEY(BLOB_ID) REFERENCES `BLOB`(id)
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS `SPRINT`(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT UNIQUE NOT NULL,
    BASE_COMMIT_ID INTEGER,
    FOREIGN KEY(BASE_COMMIT_ID) REFERENCES `COMMIT`(id)
);

CREATE TABLE IF NOT EXISTS `SPRINT_BLOB` (
    SPRINT_ID INTEGER NOT NULL,
    BLOB_ID TEXT NOT NULL,
    path TEXT NOT NULL,
    PRIMARY KEY (SPRINT_ID, path),
    FOREIGN KEY(SPRINT_ID) REFERENCES `SPRINT`(id),
    FOREIGN KEY(BLOB_ID) REFERENCES `BLOB`(id)
) WITHOUT ROWID;
